import './globals.css'
import type { Metadata } from 'next'
import { Nunito_Sans } from 'next/font/google'
import '@mantine/core/styles.css';

import { MantineProvider, ColorSchemeScript } from '@mantine/core'

const nunito = Nunito_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={nunito.className}>
        <MantineProvider>{children}
        </MantineProvider></body>
    </html>
  )
}
